name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  pester_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        shell: pwsh
        run: |
          Get-ChildItem
          Import-Module ./PSHCVault -Verbose -Force
          Invoke-Pester -Passthru